### ISSUE TITLE
Eating causes bugs at high level while using ring of energy 

### ISSUE THREAD

**Issue by Someone3462** [TrashboxBobylev/Experienced-Pixel-Dungeon-Redone#25]
Hunter at level 24355 bugs the game when eating putting the hp in negative. This happens while using a ring of energy. The start new game option pops up in the menu. Going to the main menu and starting it again fixes the hp issue.

![Screenshot_20230604-151926.png](https://github.com/TrashboxBobylev/Experienced-Pixel-Dungeon-Redone/assets/88924764/052d0a57-48df-48e1-86d4-b737c79358a6)

![Screenshot_20230604-151932.png](https://github.com/TrashboxBobylev/Experienced-Pixel-Dungeon-Redone/assets/88924764/8bac6cf2-0f6b-49f0-9c46-71a1c1430777)

**Comment by TrashboxBobylev** [comment]
Fixed in dev by making recharge effect be able to do 64-bit heals.
