### ISSUE TITLE
Chanlice of blood error

### ISSUE THREAD

**Issue by DragonMaster14545** [TrashboxBobylev/Experienced-Pixel-Dungeon-Redone#28]
I have a highly upgraded chanlice of blood but as soon as I equip it, I have nagatice health and the game acts like it is still calculating. Also when I open the pause menu, it has the option start new game there. ![Screenshot_2023-07-02-14-58-49-603_com.trashboxbobylev.experiencedpixeldungeon.redone.jpg](https://github.com/TrashboxBobylev/Experienced-Pixel-Dungeon-Redone/assets/114180377/624303a6-a579-4aab-980d-7e85ded5a789)

![Screenshot_2023-07-02-14-59-00-401_com.trashboxbobylev.experiencedpixeldungeon.redone.jpg](https://github.com/TrashboxBobylev/Experienced-Pixel-Dungeon-Redone/assets/114180377/b96c4d07-b4a5-41b8-98dd-3c5c326d4428)

![Screenshot_2023-07-02-14-59-03-753_com.trashboxbobylev.experiencedpixeldungeon.redone.jpg](https://github.com/TrashboxBobylev/Experienced-Pixel-Dungeon-Redone/assets/114180377/06426cd2-09f1-432c-8091-22e0cfd31a43)

**Comment by TrashboxBobylev** [comment]
Seems to be fixed with switch to 64-bit numbers in 2.17.
