### ISSUE TITLE
Ring/Artifact Duplication Using Incredibly Cheesy Cheest

### ISSUE THREAD

**Issue by ethan-j-carlson** [TrashboxBobylev/Experienced-Pixel-Dungeon-Redone#42]
**The new item container for rings and artifacts (Incredibly Cheesy Cheest) can be used to duplicate rings and artifacts.**

Here is how the process works:

1. Start by having your equipped rings/artifacts filled out (i.e. equip 2 rings & 1 artifact or 1 ring & two artifacts)
2. Try to equip another ring/artifact, and select something from the "Unequip one item" UI. The item you just equipped will be **the target for duplication**
3. The target should now be equipped. However, inside the incredibly cheesy cheest, there will exist a "pointer" of the target. The target will have a light gray background akin to any other equipped item, but is not (strictly) grouped with the other equipped items. Any interactions with the "pointer" will be the same as interacting with the equipped target itself
4. Exit the save/return to the main menu
5. Reenter the save
6. The "pointer" should now be an exact copy of the artifact/ring that is independent from the original item.

Apart from the obvious benefit of having infinite artifacts/rings, this also allows for weapon/armor duplication via the Dried Rose. The items outfitted using the Dried Rose will be cloned alongside a copy of the Dried Rose. This allows the player to rapidly scale once they have the duplication set up and reach the blacksmith quest, as they can use the Forge option to exponentially scale their equipment, and they can use the Extract option on duplicates of that equipment to upgrade anything else.

**Comment by Stigmund** [comment]
Can this be put back in? LOL i loved this glitch! it added to the OP nature of the game!
