### ISSUE TITLE
Arena thief can steal key items

### ISSUE THREAD

**Issue by fesoliveira014** [TrashboxBobylev/Experienced-Pixel-Dungeon-Redone#52]
The arena thief can steal key items such as the Scroll Holder and Waterskin. While it's okay to have an enemy there that you must watch out for, they can ruin a run by stealing one of these items, so this is either really unbalanced or a bug.

**Comment by Hexabiterax** [comment]
You can get that things back when you go to a Trader on the First floors of the different dungeons

**Comment by fesoliveira014** [comment]
Yeah, I noticed that after I kept playing a bit longer, but it just feels bad to have those stolen. If that is intended behaviour that is fine, but I figured I could at least provide the feedback.

**Comment by yogdzewa** [comment]
Most dangerous enemy lol. I have to keep checking whether he is running at me.
