### ISSUE TITLE
Cheat/workaround

### ISSUE THREAD

**Issue by MarsKamara** [TrashboxBobylev/Experienced-Pixel-Dungeon-Redone#58]
You can get the elixir of luck randomly. If you drink it then it is harder to obtain one. But if you don't drink it and drop it while trading with the rat king then he will give you some. Just keep dropping them and not drinking them and you can stack them up. It's a nice headstart for the people who played the game for a while.
Plz don't remove unless you have too. I think i'm the only one that knows about this.

**Comment by TrashboxBobylev** [comment]
Fixed in dev by making elixir of luck's drop be no longer affected by luck.
