### ISSUE TITLE
Do you need a beta tester.

### ISSUE THREAD

**Issue by MarsKamara** [TrashboxBobylev/Experienced-Pixel-Dungeon-Redone#59]
I have been playing the game since 2.10(I played a little before that also). I could find game bugs for you.

**Comment by TrashboxBobylev** [comment]
I mean, I semi-rarely look into this page for bugs to fix, so you can just send things here.

**Comment by zay448345045** [comment]
If you need a test version of the game, you can compile it yourself, and action can also be

**Comment by MarsKamara** [comment]
Thanks, Sry for the 1 month late response

**Comment by zay448345045** [comment]
> Thanks, Sry for the 1 month late response

The fork version of my homepage already has a pre compiled debug version, which you can find in the release
