### ISSUE TITLE
Staff imbued with everything wand's battlemage special text is missing

### ISSUE THREAD

**Issue by Novanox4** [TrashboxBobylev/Experienced-Pixel-Dungeon-Redone#61]
If the mage's staff is imbued with the everything wand, the text that indicates what enchantment it will activate on hit if playing as a battlemage or rat king is missing
![Screenshot_20240413-175014.jpg](https://github.com/TrashboxBobylev/Experienced-Pixel-Dungeon-Redone/assets/154760485/2523673f-c447-43c0-9108-98ff49dd4095)

**Comment by TrashboxBobylev** [comment]
Added in dev.
