### ISSUE TITLE
Game Stuck "Loading" after Destroying Pylon vs DM-300

### ISSUE THREAD

**Issue by shonigmann** [TrashboxBobylev/Experienced-Pixel-Dungeon-Redone#62]
I ran into an interesting bug while playing rat king on 2.17.2 (android).

After Destroying a pylon with the Starlight Smasher during the DM-300 boss fight, the game soft-locked, with the screen shake animation and "loading" pinwheel running non stop. Menus still work, but all character actions are locked. Exiting and returning to the saved game resumes the "locked" condition. 

Interestingly, my character has the paralyzed condition for 2147479680 turns (almost ~2^31)

![Screenshot_20240421-161655](https://github.com/TrashboxBobylev/Experienced-Pixel-Dungeon-Redone/assets/28554033/80792b1e-cc89-49d0-abdb-b39d294bbb91)

**Comment by TrashboxBobylev** [comment]
Known thing, fixed in-dev.
