### ISSUE TITLE
Wtf?, Ring of Haste buggy

### ISSUE THREAD

**Issue by marcosdavid39** [TrashboxBobylev/Experienced-Pixel-Dungeon-Redone#63]
![Screenshot_2024-05-04-13-04-56-389_com trashboxbobylev experiencedpixeldungeon redone](https://github.com/TrashboxBobylev/Experienced-Pixel-Dungeon-Redone/assets/82599963/c9e0a677-988d-4618-acd8-39408848363a)
Ring of Haste decreasing movement speed instead of increasing

**Comment by TrashboxBobylev** [comment]
Intended.
