### ISSUE TITLE
Luck decreases chance of getting refined loot bag

### ISSUE THREAD

**Issue by Bulkatraz** [TrashboxBobylev/Experienced-Pixel-Dungeon-Redone#64]
This code uses Dungeon.Float() which returns higher rolls with higher luck which reduces chance of getting a refined bag. Use Dungeon.Float() with LuckDirection.DOWN and replace (lol > worstRoll) with (lol < worstRoll) to increase the chance of getting a refined bag with higher luck
```
    public static Item burningRoll(){
        float worstRoll = 0f;
        for (int i = 0; i < 3; i++){
            float lol = Dungeon.Float();
            if (lol > worstRoll) worstRoll = lol;
        }

        if (worstRoll <= 0.35f)
            return new IdealBag();
        else
            return new BurntBag();
    }
```

**Comment by TrashboxBobylev** [comment]
This roll is actually getting removed in next update, hah...
