### ISSUE TITLE
Rat king's soul mark

### ISSUE THREAD

**Issue by SanyTarn** [TrashboxBobylev/Experienced-Pixel-Dungeon-Redone#67]
Soul mark at least when used by RK doesn't seem to do anything in terms of hunger or regeneration.

Also it may be a good idea to list the perks RK has.

**Comment by TrashboxBobylev** [comment]
Only Warlock is supposed to get satiety from soul mark. However, I did tweak the mechanic to support 64-bit properly indev.

RK has nothing on him, it is literally 5 classes with original abilities combined.
