### ISSUE TITLE
Telekinetic Grab full inventory crash

### ISSUE THREAD

**Issue by Crystal4546** [TrashboxBobylev/Experienced-Pixel-Dungeon-Redone#69]
Telekinetic Grab crashes the game when it tries to pick up an item when you have a full inventory (also affects the water skin) 

https://github.com/TrashboxBobylev/Experienced-Pixel-Dungeon-Redone/assets/172195349/869c774b-a503-4033-8cbc-05c829ddbb51

**Comment by TrashboxBobylev** [comment]
Fixed in dev.
