### ISSUE TITLE
Latest version 2.10.2 breaks in the 5th dungeon loop

### ISSUE THREAD

**Issue by epd42** [TrashboxBobylev/Experienced-Pixel-Dungeon-Redone#7]
Been playing for a while and really enjoyed the change of pace.
Up until I reset the dungeon for the 5th time, where the game becomes unplayable.

The issues started with leveling up. Beating a single scorpion in the arena gained me around 200 levels at once. Which froze the game for around 10-30 seconds each time.
After that, applying the 200k+ scrolls of upgrade at once gained from a few of those kills froze the game for a solid 3 minutes.
So far, nothing absolutely game-breaking, but already more or less unplayable.
I already started noticing a pattern though: the more upgrades I had on my items, the longer the loading times I had.
Which brought me to the point where I can't play that save any more: I put a bunch of upgrades (somewhere between 50k-200k, can't remember exactly) on the last fishing rod and went fishing. Which yielded items with more than 10 million upgrades on them.
You can see where this is going: with this many upgrades on some items, the save just won't load any more in a reasonable time frame. Maybe if I waited for a few hours, but that's just not going to happen.
Samsung Galaxy Tab S3 btw., surely not the latest and greatest, but I don't see the problems just vanish with slightly more powerful hardware, as I was just getting started with grinding in the 5th loop.

If I may propose a solution to this:
Tune down the whole scaling a bit. Maybe to a point where the number of upgrades, enemy strength etc. in the 5th loop is about what it is now in the fourth loop. Or maybe even the 3rd loop, because the 4th loop already started showing some of the issues I had here. And by using the fishing rod, one could easily start breaking the game earlier.

**Comment by NyanMC** [comment]
old issue but high loops are just broken in general, i hope you like wearing armor that blocks -2147483648 damage or getting a crit on tengu that makes him totally invulnerable

**Comment by DragonMaster14545** [comment]
I think it also depends on the device you are using. My pretty good mobile only starts stuttering at 10m upgrade scrolls.
