### ISSUE TITLE
Wooden Fishing Rod not Casting

### ISSUE THREAD

**Issue by Dr3e6t** [TrashboxBobylev/Experienced-Pixel-Dungeon-Redone#70]
i was using my fishing rod then a crazy thief stole it while it was casted, after defeating the thief and getting it back my fishing rod is now always casted but i dont see the hook casted. i tried pressing Uncast multiple times, restarting my phone, selling the fishing rod to the trader then buying it again from him, throwing, dropping, even using the fate lock to reset the level doesn't fix it to cast the rod again.

i also wasted 3 upgrades in hopes it fixes it but it did not

**Comment by TrashboxBobylev** [comment]
Fixed in dev by making any fishing rod remove hook and becoming available for casting, if it disappears from player's inventory by any means.
